import type { NextPage } from "next";
import { useRef } from "react";
import Head from "next/head";

import Navbar from "../components/Navbar";
import Hero from "../components/Hero";
import About from "../components/About";
import Review from "../components/Review";
import Contact from "../components/Contact";

const Home: NextPage = () => {
  const hero = useRef<HTMLDivElement>(null);
  const about = useRef<HTMLDivElement>(null);
  const review = useRef<HTMLDivElement>(null);
  const contact = useRef<HTMLDivElement>(null);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-white min-h-screen">
        <Navbar reference={{ hero, about, review, contact }} />
        <Hero refElement={hero} />
        <About refElement={about} />
        <Review refElement={review} />
        <Contact refElement={contact} />
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
